### PR TITLE
Allow syncing different names

### PR DESCRIPTION
**Pull request by bumbu**
[Review on Reviewable](https://reviewable.io/reviews/danlevan/gulp-config-sync/1)

### CODE REVIEW

**Comment by 8lueberry** [comment]
Great feature :) I am away for a week but I'll merge it once I have access to a laptop :)

**Comment by bumbu** [comment]
@danlevan Ping

**Comment by bumbu** [comment]
It would be great if you would bump the version and update it on npm.
Thanks.

**Comment by 8lueberry** [comment]
I added some test and it's now version 1.0.0.. Thanks for the pr :)

**Pull request merged**
